#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jul 23 01:10:26 JST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=6
shaderPack=MakeUp-UltraFast-9.5b.zip
