[compat]
	undergarden = false
	twilightforest = false
	toughasnails = false
	mowziesmobs = false
	irons_spellbooks = false
	immersiveengineering = false
	farmersdelight = false
	ecologics = false
	create = false
	cataclysm = false
	ars_nouveau = false
