#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jul 20 02:58:37 JST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=Bliss_v2.1.2_(Chocapic13_Shaders_edit).zip
