enableAttack = false
enableGift = true
enableStrike = true

[taskMood]
TaskTridentAttack = 7.1428565E-4
TaskBowAttack = 7.1428565E-4
TaskDanmakuAttack = 7.1428565E-4
TaskCrossBowAttack = 7.1428565E-4

[moodNumber]
GOOD_ATTACK_SPEED = 8.0
STOP_SLEEP_NORMAL_MOOD = 10.0
EAT_MOOD = 5.0
JOY_MOOD = 1.0
GOOD_HAPPY_MULTIPLIER = 1.0
GOOD_ANGRY_MULTIPLIER = 1.0
MOOD_TASK_NUMBER = 1.0
BAD_HAPPY_MULTIPLIER = 0.5
MAD_ATTACK_DAMAGE_MULTIPLIER = 2.0
BAD_ANGRY_MULTIPLIER = 2.0
HURT_BY_OWNER = 30.0
SEND_GIFT_SPEED = 0.5
DIE_COOLDOWN = 12000.0
MOOD_START_STRIKE = 120.0
HURT_RECOVER_COOLDOWN = 1200.0
NORMAL_HAPPY_MULTIPLIER = 0.75
DIE_MOOD = 10.0
GOOD_ATTACK_DAMAGE_MULTIPLIER = 1.5
ATTACK_ENTITY_DIE_MOOD = 100.0
MAD_ANGRY_MULTIPLIER = 0.0
BAD_ATTACK_SPEED = 10.0
MAD_HAPPY_MULTIPLIER = 0.0
MOOD_RECOVER_VALUE = 1.0
JOY_MOOD_COOLDOWN = 1200.0
STOP_SLEEP_BY_HURT_COOLDOWN = 2400.0
NORMAL_ATTACK_DAMAGE_MULTIPLIER = 1.0
MAD_ATTACK_SPEED = 10.0
STOP_SLEEP_NORMAL_COOLDOWN = 200.0
DIE_MOOD_MAX = 110.0
ATTACK_MOVE_SPEED = 1.0
NORMAL_ANGRY_MULTIPLIER = 1.5
MOOD_ADD_FAVORABILITY_COOLDOWN_MIN = 9600.0
STRIKE_CHANCE = 0.10000000149011612
MOOD_RECOVER_COOLDOWN = 200.0
NORMAL_ATTACK_SPEED = 4.0
HURT_BY_OTHER = 5.0
HURT_COOLDOWN = 50.0
MOOD_ADD_FAVORABILITY_VALUE = 1.0
MOOD_ADD_FAVORABILITY_COOLDOWN_MAX = 12000.0
ATTACK_ENTITY = 10.0
BAD_ATTACK_DAMAGE_MULTIPLIER = 1.2999999523162842
STOP_SLEEP_BY_HURT_MOOD = 30.0
